# Generated by Django 5.2.7 on 2025-10-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heromodels',
            name='exampletext',
            field=models.CharField(max_length=200),
        ),
    ]
