# Generated by Django 5.2.7 on 2025-10-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_heromodels_exampletext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heromodels',
            name='exampletext',
            field=models.CharField(max_length=350),
        ),
    ]
