# Generated by Django 5.2.7 on 2025-11-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_heromodels_exampletext'),
    ]

    operations = [
        migrations.AddField(
            model_name='heromodels',
            name='textcody',
            field=models.CharField(default='text', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heromodels',
            name='textfamily',
            field=models.CharField(default='tex2', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heromodels',
            name='textundertake',
            field=models.CharField(default='text1', max_length=50),
            preserve_default=False,
        ),
    ]
