"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/#values
"""

from pathlib import Path
import os # Aseguramos que el módulo os esté importado al inicio

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',      
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Datos para hacer las conexiones a Docker, XATA y Render
from urllib.parse import urlparse
import dj_database_url

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'default-key-para-desarrollo')

# SECURITY WARNING: don't run with debug turned on in production!
# CORRECCIÓN: Leer DEBUG desde la variable de entorno y convertir a booleano
DEBUG_STRING = os.getenv('DEBUG', 'True').lower()
DEBUG = DEBUG_STRING in ('true', '1', 't', 'y')


# Hosts Permitidos:
# Lee los hosts de entorno, usando valores locales como fallback.
# Esto previene el error 'DisallowedHost' en desarrollo.
ALLOWED_HOSTS_RAW = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,backend').split(',')
ALLOWED_HOSTS = [h.strip() for h in ALLOWED_HOSTS_RAW if h.strip()]

# Si DEBUG es True, permitimos todos los hosts (Docker, 0.0.0.0, etc.)
if DEBUG:
    ALLOWED_HOSTS = ['*']


# Database Configuration (XATA)
DATABASE_URL = os.getenv('DATABASE_URL_POSTGRES')

if DATABASE_URL:
    # Usa dj_database_url para parsear la URL completa de XATA
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            ssl_require=True # Para XATA, es fundamental
        )
    }
else:
    # Fallback a SQLite para desarrollo si no hay variable .env
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- LECTURA Y PROCESAMIENTO DE CORS ---

# 1. Obtener la cadena de URLs separadas por comas
CORS_URLS_STRING = os.getenv('FRONTEND_URLS_CORS', '') # Usamos un string vacío por defecto

# 2. Dividir el string en una lista, eliminando entradas vacías/blancos
# Esto previene el error 'corsheaders.E006' (CORS_ALLOWED_ORIGINS should be a sequence of strings)
CORS_ALLOWED_ORIGINS = [
    url.strip() 
    for url in CORS_URLS_STRING.split(',') 
    if url.strip()
]

# 3. Advertencia si está vacío (lo mantuviste y es útil)
if not CORS_ALLOWED_ORIGINS:
    print("WARNING: CORS_ALLOWED_ORIGINS está vacío. Revisa la variable FRONTEND_URLS_CORS.")     

# 4. En producción, siempre debe ser False.
CORS_ALLOW_ALL_ORIGINS = False 


# Información agregada para que funcione la creación de la documentación
REST_FRAMEWORK = {
    # Tu configuración actual...
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Seguros Nana API',
    'VERSION': '1.0.0',
}