# frontend/Dockerfile
FROM node:20-alpine

WORKDIR /app

# Copia package.json primero (para caché)
COPY package*.json ./

# Instala dependencias
RUN npm install

# Copia el resto del código
COPY . .

# Expone el puerto de Vite (por defecto 5173)
EXPOSE 5173

# Inicia el servidor de desarrollo
CMD ["pnpm", "run", "dev"]