# Imagen base ligera con Node 20
FROM node:20-slim

# Setea el directorio de trabajo
WORKDIR /app

# Instala pnpm globalmente
RUN npm install -g pnpm

# Copia los archivos de dependencias y lockfile
COPY package.json pnpm-lock.yaml ./

# Instala dependencias
RUN pnpm install

# Copia el resto del código fuente
COPY . .

# Expone el puerto de Vite
EXPOSE 5173

# Comando de desarrollo con host accesible desde Docker
CMD ["pnpm", "run", "dev"]
